version: '3.7'

services:

  client-prod:
    container_name: client-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        REACT_APP_API_URL:  ${API_URL}
    ports:
      - '1337:80'