export { AuthorForm } from "./AuthorForm";
export { BookDetail } from "./BookDetail";
export { BookForm } from "./BookForm";
export { BorrowBook } from "./BorrowBook";
export { ChangePassword } from "./ChangePassword";
export { GenreForm } from "./GenreForm";
export { Home } from "./Home";
export { Login } from "./Login";
export { UserForm } from "./UserForm";
