// Generated by https://quicktype.io

export interface LoginResponse {
  message: string;
  token: string;
}

// Generated by https://quicktype.io

export interface BookResponse {
  books: Book[];
}

export interface BookIdResponse {
  book: Book;
}

export interface Book {
  id: number;
  title: string;
  published_year: number;
  stock?: number;
  author: string[];
  genre: string[];
}
