// Generated by https://quicktype.io

export interface LoginResponse {
  message: string;
  token: string;
  user: User;
}

// Generated by https://quicktype.io

export interface BookResponse {
  books: Book[];
}

export interface BookIdResponse {
  book: Book;
}

export interface Book {
  id: number;
  title: string;
  published_year: number;
  stock?: number;
  author: string[];
  genre: string[];
}

// Generated by https://quicktype.io

export interface UserResponse {
  user: User;
  message: string;
}

export interface User {
  id?: number;
  first_name: string;
  last_name: string;
  email: string;
  role: string;
  password?: string;
}

// Generated by https://quicktype.io

export interface AuthorResponse {
  id: number;
  name: string;
}

// Generated by https://quicktype.io

export interface GenreResponse {
  id: number;
  name: string;
}

// Generated by https://quicktype.io

export interface BorrowedResponse {
  borrowed: Borrowed[];
}

export interface Borrowed {
  title: string;
  published_year: number;
  status: string;
  email: string;
  iduser: string;
  idbook: string;
}

export interface ChangePasswordProps {
  oldPassword: string;
  newPassword: string;
}

export interface BookFormProp {
  title: string;
  published_year: number;
  stock: number;
  authorId: string[];
  genreId: string[];
}
